name: Make test binaries
on: [push]
jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create virtualenv
        run: python3 -m venv venv
      - name: Install deps
        run: .\venv\Scripts\pip install -r requirements.txt
      - name: Build bundle
        run: .\venv\Scripts\python make_release.py
      - name: Remove unwanted binaries
        run: del dist/zmake.exe
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Windows binaries
          path: dist
  Build_Linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create virtualenv
        run: python3 -m venv venv
      - name: Install deps
        run: ./venv/bin/pip install -r requirements.txt
      - name: Try to build
        run: ./venv/bin/python3 make_release.py
      - name: Remove unwanted binaries
        run: rm dist/zmake
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Linux package
          path: dist/

